import re
import json
import requests
from typing import List, Dict, Optional, Union
from datetime import datetime, timedelta, date, time
from pydantic import ValidationError
from tenacity import retry, wait_exponential, stop_after_attempt
import config
from agent.schemas import ToolCall, TaskPlan, TOOL_ARGS_SCHEMAS, ScheduleCalendarArgs, ListCalendarArgs
from agent.prompts import AGENT_SYSTEM_PROMPT, REVISE_DRAFT_SYSTEM_PROMPT
import db.session as db

@retry(wait=wait_exponential(min=1, max=8), stop=stop_after_attempt(3), reraise=True)
def _ollama_chat(messages: List[Dict[str, str]], system: str) -> str:
    """Send chat request to Ollama with forced JSON output format."""
    payload = {
        "model": config.OLLAMA_MODEL,
        "messages": [{"role": "system", "content": system}] + messages,
        "stream": False,
        "format": "json",
        "options": {"temperature": 0.15}
    }
    response = requests.post(
        f"{config.OLLAMA_BASE_URL}/api/chat",
        json=payload,
        timeout=120,
    )
    response.raise_for_status()
    return response.json()["message"]["content"]

def _clean_email_body(body: str, sender_name: Optional[str] = None) -> str:
    """
    Sanitize and format email body text:
    1. Deduplicate repeated paragraphs or blocks (prevents model repetition loops).
    2. Format greeting and sign-off on their own distinct lines with clean spacing.
    3. Ensure user's profile display name is used in the sign-off if provided.
    4. Strip extraneous 'Note:' or 'P.S.:' commentary blocks generated by LLM.
    """
    if not body:
        return ""
    
    text = body.replace("\r\n", "\n").strip()
    
    # Strip trailing Note: or P.S.: commentary generated by LLM
    text = re.sub(r"\n\s*(?:Note|P\.S\.|PS):.*$", "", text, flags=re.IGNORECASE | re.DOTALL).strip()
    
    # 1. Deduplicate identical repeated paragraph blocks split by blank lines
    blocks = [b.strip() for b in re.split(r"\n\s*\n", text) if b.strip()]
    unique_blocks = []
    for b in blocks:
        if not unique_blocks or b != unique_blocks[-1]:
            unique_blocks.append(b)
    
    text = "\n\n".join(unique_blocks)
    
    # 2. Deduplicate repeated lines
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    unique_lines = []
    for l in lines:
        if not unique_lines or l != unique_lines[-1]:
            unique_lines.append(l)
            
    full_text = "\n".join(unique_lines)
    
    # 3. Format greeting if on same line or missing comma
    m_greet = re.match(r"^(Hi|Hello|Dear|Hey)\s+([A-Za-z0-9_\-]+)(?:,?\s+|\n+)(.*)$", full_text, re.DOTALL | re.IGNORECASE)
    greeting_str = ""
    rest_str = full_text
    if m_greet:
        g_word, g_name, rest_str = m_greet.groups()
        greeting_str = f"{g_word.capitalize()} {g_name},"
    
    # 4. Format closing / sign-off at the end
    closing_pattern = r"((?:Best regards|Regards|Sincerely|Thanks|Thank you|Warm regards|With regards),?)\s*(.*)$"
    m_close = re.search(closing_pattern, rest_str, re.IGNORECASE | re.DOTALL)
    
    closing_str = ""
    body_text = rest_str
    if m_close:
        body_text = rest_str[:m_close.start()].strip()
        c_val = m_close.group(0).strip()
        m_sign = re.match(r"^((?:Best regards|Regards|Sincerely|Thanks|Thank you|Warm regards|With regards),?)\s*(.*)$", c_val, re.IGNORECASE | re.DOTALL)
        if m_sign:
            c_word, c_name = m_sign.groups()
            c_word = c_word.strip()
            if not c_word.endswith(","):
                c_word += ","
            c_name = c_name.strip()
            if sender_name:
                c_name = sender_name
            if c_name:
                closing_str = f"{c_word}\n{c_name}"
            else:
                closing_str = c_word
        else:
            closing_str = c_val
    elif sender_name:
        closing_str = f"Best regards,\n{sender_name}"

    parts = []
    if greeting_str:
        parts.append(greeting_str)
    if body_text:
        parts.append(body_text)
    if closing_str:
        parts.append(closing_str)
        
    return "\n\n".join(parts)

def _has_placeholder(tool_call: ToolCall) -> bool:
    """Check if a send_email tool call contains bracketed placeholders in subject or body."""
    if not tool_call or tool_call.tool != "send_email":
        return False
    subject = str(tool_call.args.get("subject", ""))
    body = str(tool_call.args.get("body", ""))
    pattern = r"\[.*?\]"
    return bool(re.search(pattern, subject) or re.search(pattern, body))

def _placeholder_fallback() -> ToolCall:
    """Fallback response when bracketed placeholders remain in the generated draft."""
    return ToolCall(
        tool="none",
        args={"message": "I generated an incomplete draft with a placeholder — let me try again"},
        reasoning="Generated email subject or body contained an unfilled bracketed placeholder."
    )

def resolve_relative_calendar_date(user_message: str, ref_dt: Optional[datetime] = None) -> Optional[str]:
    """
    Parse relative date references in user_message (e.g. 'Friday', 'tomorrow', 'today', 'next Friday')
    and return the calculated YYYY-MM-DD date string relative to ref_dt (defaults to now).
    """
    from datetime import datetime, timedelta
    if ref_dt is None:
        ref_dt = datetime.now().astimezone()
    msg = user_message.lower()

    if re.search(r"\btomorrow\b", msg):
        return (ref_dt + timedelta(days=1)).strftime("%Y-%m-%d")

    if re.search(r"\btoday\b", msg):
        return ref_dt.strftime("%Y-%m-%d")

    weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    for idx, day_name in enumerate(weekdays):
        pattern = r"\b(?:this\s+|next\s+)?" + day_name + r"\b"
        if re.search(pattern, msg):
            is_next = bool(re.search(r"\bnext\s+" + day_name + r"\b", msg))
            today_idx = ref_dt.weekday()

            if is_next:
                days_ahead = (idx - today_idx) % 7
                if days_ahead == 0:
                    days_ahead = 7
                else:
                    days_ahead += 7
            else:
                days_ahead = (idx - today_idx) % 7
                if days_ahead == 0:
                    days_ahead = 7

            target = ref_dt + timedelta(days=days_ahead)
            return target.strftime("%Y-%m-%d")

    return None

def parse_natural_datetime(text: str, reference_datetime: Optional[datetime] = None) -> Optional[str]:
    """
    Parse a natural-language datetime expression or relative duration string into
    a normalized ISO datetime string ('YYYY-MM-DDTHH:MM:SS').

    Supports:
    - ISO strings directly ('2026-09-11T09:00:00', '2026-09-11 09:00:00', '2026-09-11')
    - Relative duration offsets ('in 30 minutes', 'in 2 hours', 'in 90 minutes')
    - Relative date keywords ('today', 'tomorrow', 'Friday', 'this Friday', 'next Friday', weekdays)
    - 12-hour (9 AM, 9:30 AM, 2:30 PM) and 24-hour (14:30, 18:00) time formats
    - Rejects invalid times (25:00, 13:90, 15 PM) and unparseable text by returning None.
    - Preserves timezone of reference_datetime (defaults to local timezone if None).
    """
    if not text or not isinstance(text, str):
        return None

    if reference_datetime is None:
        ref_dt = datetime.now().astimezone()
    else:
        ref_dt = reference_datetime

    clean_text = text.strip()

    # 1. Direct ISO datetime format string check
    try:
        if len(clean_text) == 10 and clean_text.count("-") == 2:
            dt_iso = datetime.strptime(clean_text, "%Y-%m-%d")
            if ref_dt.tzinfo:
                dt_iso = dt_iso.replace(tzinfo=ref_dt.tzinfo)
            return dt_iso.strftime("%Y-%m-%dT%H:%M:%S")

        dt_iso = datetime.fromisoformat(clean_text)
        if dt_iso.tzinfo is None and ref_dt.tzinfo:
            dt_iso = dt_iso.replace(tzinfo=ref_dt.tzinfo)
        return dt_iso.strftime("%Y-%m-%dT%H:%M:%S")
    except ValueError:
        pass

    # 2. Relative Duration Expressions (e.g. "in 30 minutes", "in 2 hours", "in 90 minutes")
    duration_match = re.search(r"\bin\s+(\d+)\s*(minute|minutes|min|mins|hour|hours|hr|hrs)\b", clean_text, re.IGNORECASE)
    if duration_match:
        val = int(duration_match.group(1))
        unit = duration_match.group(2).lower()
        if "hour" in unit or "hr" in unit:
            target_dt = ref_dt + timedelta(hours=val)
        else:
            target_dt = ref_dt + timedelta(minutes=val)
        return target_dt.strftime("%Y-%m-%dT%H:%M:%S")

    # 3. Date Resolution (today, tomorrow, weekday names)
    msg_lower = clean_text.lower()
    target_date = None

    if re.search(r"\btomorrow\b", msg_lower):
        target_date = (ref_dt + timedelta(days=1)).date()
    elif re.search(r"\btoday\b", msg_lower):
        target_date = ref_dt.date()
    else:
        weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
        for idx, day_name in enumerate(weekdays):
            pattern = r"\b(?:this\s+|next\s+)?" + day_name + r"\b"
            if re.search(pattern, msg_lower):
                is_next = bool(re.search(r"\bnext\s+" + day_name + r"\b", msg_lower))
                today_idx = ref_dt.weekday()
                if is_next:
                    days_ahead = (idx - today_idx) % 7
                    if days_ahead == 0:
                        days_ahead = 7
                    else:
                        days_ahead += 7
                else:
                    days_ahead = (idx - today_idx) % 7
                    if days_ahead == 0:
                        days_ahead = 7
                target_date = (ref_dt + timedelta(days=days_ahead)).date()
                break

    if target_date is None:
        return None

    # 4. Time Resolution (12-hour with AM/PM vs 24-hour format)
    hour_24 = None
    minute_24 = None

    # 4a. 12-hour format (e.g., "9 AM", "9:30 AM", "09:30 am", "2:30 PM", "12 PM")
    m_12h = re.search(r"\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b", clean_text, re.IGNORECASE)
    if m_12h:
        h_val = int(m_12h.group(1))
        m_val = int(m_12h.group(2)) if m_12h.group(2) else 0
        ampm = m_12h.group(3).lower()

        if h_val < 1 or h_val > 12 or m_val < 0 or m_val > 59:
            return None

        if ampm == "am":
            hour_24 = 0 if h_val == 12 else h_val
        else:
            hour_24 = 12 if h_val == 12 else h_val + 12
        minute_24 = m_val
    else:
        # 4b. 24-hour format (e.g., "14:30", "18:00", "09:00")
        m_24h = re.search(r"\b(\d{1,2}):(\d{2})(?::(\d{2}))?\b(?!\s*(?:am|pm))\b", clean_text, re.IGNORECASE)
        if m_24h:
            h_val = int(m_24h.group(1))
            m_val = int(m_24h.group(2))
            if h_val < 0 or h_val > 23 or m_val < 0 or m_val > 59:
                return None
            hour_24 = h_val
            minute_24 = m_val

    if hour_24 is None or minute_24 is None:
        return None

    target_dt = datetime(
        target_date.year,
        target_date.month,
        target_date.day,
        hour_24,
        minute_24,
        0,
        tzinfo=ref_dt.tzinfo
    )
    return target_dt.strftime("%Y-%m-%dT%H:%M:%S")

def validate_tool_call(
    tool_call: ToolCall,
    user_message: str,
    history: List[Dict[str, str]] = None,
    chat_id: str = None,
    reference_datetime: Optional[datetime] = None,
) -> ToolCall:
    """
    Code-level validation to prevent model hallucinations.

    For send_email, the recipient address must be grounded in a TRUSTED source:
      - Tier 1 (trusted):   the current user_message literal text
      - Tier 1 (trusted):   the live contacts table for chat_id
      Conversation history is explicitly UNTRUSTED for recipient resolution —
      it may contain emails of contacts that have since been deleted.

    For draft_reply, email_id must appear literally in user_message or history.
    For calendar tools, validate args against their Pydantic schema and enforce relative date accuracy.
    For set_alarm, deterministically resolve fire_at via parse_natural_datetime and validate via SetAlarmArgs.
    """
    # --- Tier 1: trusted sources only (current message + live contacts) ---
    trusted_text = user_message.lower()
    if chat_id:
        saved_contacts = db.get_contacts(chat_id)
        for c in saved_contacts:
            trusted_text += " " + c["email"].lower()

    # --- Tier 2: untrusted history (used ONLY for draft_reply id lookup) ---
    history_text = ""
    if history:
        for item in history:
            history_text += " " + str(item.get("content", "")).lower()

    if tool_call.tool == "send_email":
        to_address = str(tool_call.args.get("to", "")).strip().lower()
        # SECURITY: only accept the address if it appears in the current message
        # or is a live saved contact.  History text is deliberately excluded here
        # to prevent deleted-contact emails from resurfacing via old turns.
        if not to_address or to_address not in trusted_text:
            print(
                f"[Validation] Blocked send_email to '{to_address}' — "
                "address not found in current user message or live contacts table "
                "(history excluded to prevent deleted-contact leak)."
            )
            overridden = ToolCall(
                tool="none",
                args={"message": "Could you please provide the recipient's actual email address?"},
                reasoning="Recipient email address was not explicitly provided in the current message or saved contacts (prevented hallucination / deleted-contact leak)."
            )
            if hasattr(tool_call, "_was_retried"):
                overridden._was_retried = tool_call._was_retried
            return overridden

    elif tool_call.tool == "draft_reply":
        email_id = str(tool_call.args.get("email_id", "")).strip().lower()
        combined = trusted_text + history_text
        if not email_id or email_id not in combined:
            overridden = ToolCall(
                tool="none",
                args={"message": "Could you please specify which email ID you want to reply to?"},
                reasoning="Email ID was not explicitly provided in the user's input message or history (prevented hallucination)."
            )
            if hasattr(tool_call, "_was_retried"):
                overridden._was_retried = tool_call._was_retried
            return overridden

    elif tool_call.tool == "set_alarm":
        fire_at_val = str(tool_call.args.get("fire_at", "")).strip()
        parsed_dt = parse_natural_datetime(fire_at_val, reference_datetime=reference_datetime) or parse_natural_datetime(user_message, reference_datetime=reference_datetime)
        if parsed_dt:
            tool_call.args["fire_at"] = parsed_dt

        schema = TOOL_ARGS_SCHEMAS.get("set_alarm")
        if schema:
            try:
                schema.model_validate(tool_call.args)
            except ValidationError as ve:
                print(f"[Validation] Invalid arguments for set_alarm: {ve}")
                overridden = ToolCall(
                    tool="none",
                    args={"message": "Invalid arguments provided for tool set_alarm."},
                    reasoning=f"Argument validation failed for set_alarm: {ve}"
                )
                if hasattr(tool_call, "_was_retried"):
                    overridden._was_retried = tool_call._was_retried
                return overridden

    elif tool_call.tool in ("schedule_calendar", "list_calendar"):
        schema = TOOL_ARGS_SCHEMAS.get(tool_call.tool)
        if schema:
            try:
                schema.model_validate(tool_call.args)
            except ValidationError as ve:
                print(f"[Validation] Invalid arguments for {tool_call.tool}: {ve}")
                overridden = ToolCall(
                    tool="none",
                    args={"message": f"Invalid arguments provided for tool {tool_call.tool}."},
                    reasoning=f"Argument validation failed for {tool_call.tool}: {ve}"
                )
                if hasattr(tool_call, "_was_retried"):
                    overridden._was_retried = tool_call._was_retried
                return overridden

        from datetime import datetime
        if tool_call.tool == "schedule_calendar":
            date_val = str(tool_call.args.get("date", "")).strip()
            if date_val:
                try:
                    dt_obj = datetime.strptime(date_val, "%Y-%m-%d")
                    gen_weekday = dt_obj.strftime("%A").lower()

                    resolved_date = resolve_relative_calendar_date(user_message)
                    if resolved_date and resolved_date != date_val:
                        res_dt = datetime.strptime(resolved_date, "%Y-%m-%d")
                        res_weekday = res_dt.strftime("%A").lower()

                        if gen_weekday != res_weekday:
                            print(
                                f"[Validation] Correcting calendar date from '{date_val}' ({gen_weekday}) "
                                f"to '{resolved_date}' ({res_weekday}) based on user input."
                            )
                            tool_call.args["date"] = resolved_date
                except ValueError:
                    pass

        elif tool_call.tool == "list_calendar":
            resolved_date = resolve_relative_calendar_date(user_message)
            if resolved_date:
                start_dt = str(tool_call.args.get("start_datetime", "")).strip()
                if start_dt and len(start_dt) >= 10:
                    curr_start_date = start_dt[:10]
                    try:
                        dt_obj = datetime.strptime(curr_start_date, "%Y-%m-%d")
                        gen_weekday = dt_obj.strftime("%A").lower()
                        res_dt = datetime.strptime(resolved_date, "%Y-%m-%d")
                        res_weekday = res_dt.strftime("%A").lower()
                        if gen_weekday != res_weekday:
                            tool_call.args["start_datetime"] = f"{resolved_date}T00:00:00"
                            tool_call.args["end_datetime"] = f"{resolved_date}T23:59:59"
                    except ValueError:
                        pass

    return tool_call

def _resolve_tool_call_contact(tool_call: ToolCall, user_message: str, chat_id: Optional[str] = None) -> ToolCall:
    """
    Resolve a recipient name/role to an email via the live contacts table.

    Only runs when the model produced a non-email value in `to` (i.e. a name
    or role string).  When `to` already contains '@' it is a raw email address
    provided explicitly by the user — we leave it alone and let validate_tool_call
    decide whether it is trusted.
    """
    if not tool_call or tool_call.tool != "send_email" or not chat_id:
        return tool_call

    to_val = str(tool_call.args.get("to", "")).strip()

    # Only attempt contact resolution when `to` is NOT already an email address.
    # Previously the condition was `"@" not in to_val or to_val` which is always
    # True for any non-empty string — causing live-contact lookup to run even when
    # the model had already placed a valid (but deleted) email in `to`.
    if "@" not in to_val:
        matched = db.find_contact_by_name(chat_id, to_val) or db.find_contact_by_name(chat_id, user_message)
        if matched:
            tool_call.args["to"] = matched["email"]
            db.upsert_contact(chat_id, matched["name"], matched["email"])

    return tool_call

def call_agent(user_message: str, history: List[Dict[str, str]] = None, chat_id: Optional[str] = None) -> Union[ToolCall, TaskPlan]:
    """
    Main entry point for agent tool choice.
    Returns a validated ToolCall for single-tool requests, or a TaskPlan for
    multi-task requests. Callers should use isinstance() to distinguish.
    """
    if history is None:
        history = []

    # Auto-extract user display name if stated
    if chat_id:
        detected_name = db.extract_user_name_from_text(user_message)
        if detected_name:
            db.save_user_profile(chat_id, detected_name)

    # Auto-extract contact if prompt contains both name and email
    if chat_id:
        m_email = re.search(r"([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})", user_message)
        if m_email:
            email_str = m_email.group(1)
            c_name = None

            # Pattern priority order — most specific first

            # 1. "HR name is Shylaja mail id is email@x.com"  /  "name is X ... email"
            m = re.search(
                r"\bname\s+is\s+([A-Za-z][A-Za-z0-9_.\-\s]{1,38}?)\s+(?:and\s+)?(?:her|his|their)?\s*(?:mail|email|mail\s+id|email\s+id)\s+is\s+" + re.escape(email_str),
                user_message, re.IGNORECASE
            )
            if m:
                c_name = m.group(1).strip()

            # 2. "X mail id is email" / "X email id is email"
            if not c_name:
                m = re.search(
                    r"([A-Za-z][A-Za-z0-9_.\-\s]{1,38}?)\s+(?:mail|email)\s+(?:id\s+)?is\s+" + re.escape(email_str),
                    user_message, re.IGNORECASE
                )
                if m:
                    c_name = m.group(1).strip()

            # 3. "HR name is Shylaja" anywhere in message (no email proximity required)
            if not c_name:
                m = re.search(
                    r"\bhr\s+name\s+is\s+([A-Za-z][A-Za-z0-9_.\-\s]{1,38?}?)(?:\s+(?:and|mail|email|her|his)|$)",
                    user_message, re.IGNORECASE
                )
                if m:
                    c_name = m.group(1).strip()

            # 4. Classic "email/mail/send to NAME <email>" pattern
            if not c_name:
                m = re.search(
                    r"(?:email|mail|send to|to)\s+([A-Za-z0-9_.\-\s]+?)\s+<?" + re.escape(email_str) + r">?",
                    user_message, re.IGNORECASE
                )
                if m:
                    c_name = m.group(1).strip()

            if c_name:
                # Strip leading verb phrases
                c_name = re.sub(r"^(?:send|email|mail|draft|write)\s+(?:to\s+)?(?:a\s+mail\s+to\s+)?", "", c_name, flags=re.IGNORECASE).strip()
                # Strip a bare leading "to" left over from "mail to NAME <email>"
                c_name = re.sub(r"^to\s+", "", c_name, flags=re.IGNORECASE).strip()
                # Strip common trailing noise words that indicate the name hasn't been fully captured
                c_name = re.sub(r"\s+(?:a\s+mail|his\s+mail|her\s+mail|their\s+mail|mail\s+id|email\s+id|is|id|that|and)$", "", c_name, flags=re.IGNORECASE).strip()
                # Reject single-word noise tokens that aren't real names
                _noise = {"is", "and", "the", "an", "a", "to", "email", "mail", "her", "his", "their", "id", "that"}
                if c_name and len(c_name) < 40 and c_name.lower() not in {"an email", "a mail", "email", "the"} and c_name.lower() not in _noise:
                    db.upsert_contact(chat_id, c_name, email_str)

    from datetime import datetime
    now_dt = datetime.now().astimezone()
    system_prompt = AGENT_SYSTEM_PROMPT + f"\n\nCurrent Date and Time Context: {now_dt.strftime('%Y-%m-%d %H:%M:%S')} ({now_dt.strftime('%A')})"
    sender_name = None
    if chat_id:
        user_prof = db.get_user_profile(chat_id)
        if user_prof:
            sender_name = user_prof.get("display_name")
            system_prompt += f"\n\nUser Profile / Sender Name: {sender_name}"
        
        saved_contacts = db.get_contacts(chat_id)
        if saved_contacts:
            contacts_str = ", ".join([f"{c['name']} <{c['email']}>" for c in saved_contacts])
            system_prompt += f"\nSaved Contacts Context:\n{contacts_str}"

    messages = history + [{"role": "user", "content": user_message}]
    raw_response = _ollama_chat(messages, system_prompt)

    res = None
    try:
        # --- Phase 2.3: attempt TaskPlan first, then fall back to ToolCall ---
        # A TaskPlan contains a "tasks" key; a ToolCall contains "tool".
        # Pydantic naturally distinguishes them via their required fields.
        try:
            res = TaskPlan.model_validate_json(raw_response)
            # Phase 2.4: validate every task through the existing pipeline.
            return _validate_task_plan(res, user_message, history, chat_id, sender_name)
        except (ValidationError, json.JSONDecodeError):
            pass  # Not a TaskPlan; fall through to ToolCall parsing below

        res = ToolCall.model_validate_json(raw_response)
        res._was_retried = False
        res = _resolve_tool_call_contact(res, user_message, chat_id=chat_id)
        res = validate_tool_call(res, user_message, history=history, chat_id=chat_id)
    except (ValidationError, json.JSONDecodeError) as e:
        # Single correction retry loop
        correction_msg = (
            f"Your previous output was invalid or missing required fields. Error: {e}.\n"
            "Respond ONLY with valid JSON matching {"
            '"tool": "<name>", "args": {...}, "reasoning": "..."}'
        )
        messages.append({"role": "assistant", "content": raw_response})
        messages.append({"role": "user", "content": correction_msg})
        try:
            raw_retry = _ollama_chat(messages, system_prompt)
            # Apply the same TaskPlan-first logic on the retry response
            try:
                res = TaskPlan.model_validate_json(raw_retry)
                return _validate_task_plan(res, user_message, history, chat_id, sender_name)
            except (ValidationError, json.JSONDecodeError):
                pass
            res = ToolCall.model_validate_json(raw_retry)
            res._was_retried = True
            res = _resolve_tool_call_contact(res, user_message, chat_id=chat_id)
            res = validate_tool_call(res, user_message, history=history, chat_id=chat_id)
        except Exception:
            try:
                data = json.loads(raw_response)
                if "tasks" in data and isinstance(data["tasks"], list):
                    res = TaskPlan.model_validate(data)
                    return _validate_task_plan(res, user_message, history, chat_id, sender_name)
                elif "tool" in data and "args" in data:
                    res = ToolCall(
                        tool=data["tool"],
                        args=data["args"],
                        reasoning=data.get("reasoning", "No reasoning provided.")
                    )
                    res = _resolve_tool_call_contact(res, user_message, chat_id=chat_id)
                    res = validate_tool_call(res, user_message, history=history, chat_id=chat_id)
                else:
                    raise ValueError("Invalid format")
            except Exception:
                res = ToolCall(
                    tool="none",
                    args={"message": "I had trouble structuring that request. Could you rephrase it?"},
                    reasoning=f"Failed to parse LLM response: {e}"
                )

    # The remainder of the pipeline applies only to ToolCall results.
    # TaskPlan results have already been returned above.

    # Safeguard check: detect bracketed template placeholders (e.g. [insert contact info])
    if res and isinstance(res, ToolCall) and res.tool == "send_email" and _has_placeholder(res):
        placeholder_retry_msg = (
            "Your previous email draft contained unfilled template placeholders in brackets (e.g. '[...]'). "
            "You must write a complete, final email without any bracketed placeholders or template tags. "
            "Regenerate the email draft now, omitting all brackets or placeholders."
        )
        retry_messages = list(messages) + [
            {"role": "assistant", "content": raw_response},
            {"role": "user", "content": placeholder_retry_msg}
        ]
        try:
            raw_retry = _ollama_chat(retry_messages, system_prompt)
            cleaned_retry = _clean_json_str(raw_retry)
            res_retry = ToolCall.model_validate_json(cleaned_retry)
            res_retry._was_retried = True
            res_retry = _resolve_tool_call_contact(res_retry, user_message, chat_id=chat_id)
            res_retry = validate_tool_call(res_retry, user_message, history=history, chat_id=chat_id)
            if res_retry.tool == "send_email" and _has_placeholder(res_retry):
                return _placeholder_fallback()
            res = res_retry
        except Exception:
            return _placeholder_fallback()

    if res and isinstance(res, ToolCall) and res.tool == "send_email" and "body" in res.args:
        res.args["body"] = _clean_email_body(res.args["body"], sender_name=sender_name)

    if isinstance(res, ToolCall):
        res = _post_process_contact_intent(res, user_message)

    return res

def _post_process_contact_intent(tool_call: ToolCall, user_message: str) -> ToolCall:
    """Safeguard to ensure database export and contact deletion intents are always correctly routed."""
    if not tool_call:
        return tool_call
        
    msg_lower = user_message.lower().strip()
    
    # 1. Export database / CSV download intent safeguard
    export_triggers = [
        "database", "my database", "the database", "export contact", "export contacts", 
        "contacts database", "database of my contact", "database of the mail contacts",
        "contacts file", "contacts sheet", "i need my database", "get me the database",
        "get my the database", "get me csv link", "csv link", "csv", "download link"
    ]
    if any(trigger in msg_lower for trigger in export_triggers):
        if tool_call.tool in ["search_inbox", "none", "send_email"]:
            return ToolCall(
                tool="export_contacts",
                args={},
                reasoning="User requested export of their contacts database CSV file."
            )
            
    # 2. Delete contact intent safeguard
    delete_actions = ["delete", "remove", "forget", "clear", "erase"]
    if any(act in msg_lower for act in delete_actions):
        if tool_call.tool in ["search_inbox", "none"]:
            query_str = user_message
            m_del = re.search(r"(?:delete|remove|forget|clear|erase)\s+(?:the\s+)?(.*?)(?:\s+(?:data|contact|contacts|from contact|from contacts|info|details))?$", msg_lower)
            if m_del and m_del.group(1).strip():
                query_str = m_del.group(1).strip()
            query_str = re.sub(r"\s+\b(?:data|contact|contacts|info|details)\b$", "", query_str, flags=re.IGNORECASE).strip()
            return ToolCall(
                tool="delete_contact",
                args={"query": query_str},
                reasoning=f"User requested removal of contact data for '{query_str}'."
            )

    # 3. Rename contact intent safeguard
    rename_triggers = [
        # "rename hr to Shalini" / "rename hr contact to Shalini"
        (r"(?:rename)\s+(?:the\s+)?(.+?)\s+(?:contact\s+)?to\s+(.+)", 1, 2),
        # "change hr name to Shalini" / "change the name of hr to Shalini"
        (r"change\s+(?:the\s+)?(?:name\s+of\s+)?(.+?)\s+name\s+to\s+(.+)", 1, 2),
        (r"change\s+(?:the\s+)?(.+?)\s+(?:contact\s+)?to\s+(.+)", 1, 2),
        # "update hr name to Shalini"
        (r"update\s+(?:the\s+)?(?:name\s+of\s+)?(.+?)\s+(?:name\s+)?to\s+(.+)", 1, 2),
        # "hr is now called Shalini" / "hr is now Shalini" / "hr is renamed to Shalini"
        (r"(.+?)\s+(?:is\s+now\s+called|is\s+now|is\s+renamed\s+to|new\s+name\s+is)\s+(.+)", 1, 2),
        # "new hr name is Shalini"
        (r"new\s+(.+?)\s+name\s+is\s+(.+)", 1, 2),
    ]
    if tool_call.tool in ["search_inbox", "none", "send_email"]:
        for pattern, q_group, n_group in rename_triggers:
            m_ren = re.search(pattern, msg_lower)
            if m_ren:
                query_str = m_ren.group(q_group).strip()
                new_name_str = m_ren.group(n_group).strip()
                # Strip noise trailing words
                query_str = re.sub(r"\s+\b(?:contact|contacts|name)\b$", "", query_str, flags=re.IGNORECASE).strip()
                new_name_str = re.sub(r"\s+\b(?:contact|contacts)\b$", "", new_name_str, flags=re.IGNORECASE).strip()
                if query_str and new_name_str:
                    return ToolCall(
                        tool="rename_contact",
                        args={"query": query_str, "new_name": new_name_str},
                        reasoning=f"User requested renaming contact '{query_str}' to '{new_name_str}'."
                    )

    return tool_call


def _validate_task_plan(
    plan: TaskPlan,
    user_message: str,
    history: List[Dict[str, str]],
    chat_id: Optional[str],
    sender_name: Optional[str],
) -> Union[TaskPlan, ToolCall]:
    """
    Phase 2.4 — Apply the existing single-ToolCall validation pipeline
    independently to every task inside a TaskPlan.

    Pipeline applied to each task (mirrors call_agent single-ToolCall path):
      1. _resolve_tool_call_contact  — resolve name→email via contacts DB
      2. validate_tool_call          — security: blocks hallucinated emails / email_id
      3. _has_placeholder            — detects unfilled [bracket] placeholders
      4. _clean_email_body           — deduplicates and formats email body

    _post_process_contact_intent is intentionally NOT applied per-task because
    it re-routes based on the full user_message text (e.g. if the message contains
    the word "database" it would override a valid search_inbox task to
    export_contacts). The model's intent as parsed is trusted for multi-task plans.

    Whole-plan rejection:
        If ANY task fails validation (i.e. validate_tool_call or the placeholder
        check overrides it to tool="none"), the entire plan is rejected. The
        caller receives a single none-ToolCall with an explanatory message.
        Tasks are never silently dropped or partially approved.
    """
    validated_tasks: List[ToolCall] = []

    for i, task in enumerate(plan.tasks):
        # Step 1 — contact resolution (name→email)
        task = _resolve_tool_call_contact(task, user_message, chat_id=chat_id)

        # Step 2 — security validation
        task = validate_tool_call(task, user_message, history=history, chat_id=chat_id)

        # Step 3 — placeholder check (no Ollama retry for sub-tasks;
        #          treat a placeholder as a validation failure)
        if task.tool == "send_email" and _has_placeholder(task):
            print(
                f"[TaskPlan Validation] Task {i + 1} contains unfilled placeholders — "
                "rejecting entire plan."
            )
            return ToolCall(
                tool="none",
                args={
                    "message": (
                        f"Task {i + 1} of your request contained an incomplete email "
                        "draft (unfilled placeholder). Please provide the full details."
                    )
                },
                reasoning=f"Task {i + 1} email draft had a bracketed placeholder — plan rejected.",
            )

        # Step 4 — clean email body
        if task.tool == "send_email" and "body" in task.args:
            task.args["body"] = _clean_email_body(task.args["body"], sender_name=sender_name)

        # Whole-plan rejection: if validation overrode this task to "none",
        # the entire plan is unsafe to execute.
        if task.tool == "none":
            print(
                f"[TaskPlan Validation] Task {i + 1} failed validation "
                f"(overridden to 'none') — rejecting entire plan."
            )
            return ToolCall(
                tool="none",
                args={
                    "message": (
                        task.args.get("message")
                        or (
                            f"Task {i + 1} of your request could not be validated. "
                            "Could you provide more details?"
                        )
                    )
                },
                reasoning=(
                    f"Task {i + 1} failed validation — the entire plan was rejected "
                    "to prevent partial execution."
                ),
            )

        validated_tasks.append(task)

    # All tasks passed — return the plan with validated (potentially updated) tasks.
    return TaskPlan(tasks=validated_tasks, reasoning=plan.reasoning)

def _clean_json_str(text: str) -> str:
    """Helper to strip markdown code blocks from model JSON output."""
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    return text.strip()

def _normalize_text(text: str) -> str:
    """Normalize text for whitespace and case insensitive comparison."""
    return " ".join(str(text or "").lower().split())

def revise_draft(original_draft: dict, user_feedback: str, chat_id: Optional[str] = None) -> ToolCall:
    """Revise an existing draft given feedback."""
    sender_name = None
    if chat_id:
        user_prof = db.get_user_profile(chat_id)
        if user_prof:
            sender_name = user_prof.get("display_name")

    system_prompt = REVISE_DRAFT_SYSTEM_PROMPT.format(
        to=original_draft.get("to", ""),
        subject=original_draft.get("subject", ""),
        body=original_draft.get("body", ""),
        feedback=user_feedback
    )
    if sender_name:
        system_prompt += f"\nNote: User Sender Name is '{sender_name}'. Ensure email sign-off uses '{sender_name}'."

    messages = [{"role": "user", "content": f"Please update the draft according to these instructions: {user_feedback}"}]
    raw_response = _ollama_chat(messages, system_prompt)

    res = None
    try:
        cleaned = _clean_json_str(raw_response)
        res = ToolCall.model_validate_json(cleaned)
    except (ValidationError, json.JSONDecodeError) as e:
        # Single correction retry loop for JSON format
        correction_msg = (
            f"Your previous output was invalid JSON or missing required fields: {e}.\n"
            "Respond ONLY with valid JSON matching: "
            '{"tool": "send_email", "args": {"to": "...", "subject": "...", "body": "..."}, "reasoning": "..."}'
        )
        messages.append({"role": "assistant", "content": raw_response})
        messages.append({"role": "user", "content": correction_msg})
        raw_retry = _ollama_chat(messages, system_prompt)
        try:
            cleaned_retry = _clean_json_str(raw_retry)
            res = ToolCall.model_validate_json(cleaned_retry)
        except Exception:
            # Safe fallback: preserve existing draft fields without concatenating notes
            res = ToolCall(
                tool="send_email",
                args={
                    "to": original_draft.get("to", ""),
                    "subject": original_draft.get("subject", ""),
                    "body": original_draft.get("body", ""),
                    "is_unchanged": True
                },
                reasoning="I couldn't confidently make that change — could you rephrase what you'd like edited?"
            )

    # Safeguard check: detect bracketed template placeholders (e.g. [insert contact info])
    if res and res.tool == "send_email" and _has_placeholder(res):
        placeholder_retry_msg = (
            "Your revised email draft contained unfilled template placeholders in brackets (e.g. '[...]'). "
            "You must write a complete, final email without any bracketed placeholders. "
            "Regenerate the email draft now, omitting all brackets or placeholders."
        )
        retry_messages = list(messages) + [
            {"role": "assistant", "content": raw_response},
            {"role": "user", "content": placeholder_retry_msg}
        ]
        try:
            raw_retry = _ollama_chat(retry_messages, system_prompt)
            cleaned_retry = _clean_json_str(raw_retry)
            res_retry = ToolCall.model_validate_json(cleaned_retry)
            if res_retry.tool == "send_email" and _has_placeholder(res_retry):
                return _placeholder_fallback()
            res = res_retry
        except Exception:
            return _placeholder_fallback()

    if res and res.tool == "send_email":
        if not res.args.get("to"):
            res.args["to"] = original_draft.get("to", "")

    if res and res.tool == "send_email" and "body" in res.args:
        res.args["body"] = _clean_email_body(res.args["body"], sender_name=sender_name)

    if res and res.tool == "send_email":
        orig_body = original_draft.get("body", "")
        new_body = res.args.get("body", "")
        orig_subj = original_draft.get("subject", "")
        new_subj = res.args.get("subject", "")

        if _normalize_text(orig_body) == _normalize_text(new_body) and _normalize_text(orig_subj) == _normalize_text(new_subj):
            res.reasoning = "I couldn't confidently make that change — could you rephrase what you'd like edited?"
            res.args["is_unchanged"] = True

    return res
